enable: false
licenses:
  license: free
  secret_key:

# Database support
# - sqlite
# - mysql
# - postgresql
database:
  type: sqlite

  sqlite:
    path: skill.db

  mysql:
    host: localhost
    port: "3306"
    name: mcengine
    user: root
    password: ""

  postgresql:
    host: localhost
    port: "5432"
    name: mcengine
    user: postgres
    password: ""
